power:
  description: "Sends a new power state to device"
  fields:
    device:
      required: true
      description: "The entity ID to switch"
      example: "binary_sensor.my_device_power"
      selector:
        device:
          filter:
            integration: meshcentral
    mode:
      required: true
      description: "The selected mode"
      example: "off"
      selector:
        select:
          mode: dropdown
          options:
            - wake
            - "off"
            - sleep
            - reset

notify:
  description: "Send a notification"
  fields:
    device:
      required: true
      description: "The entity ID to send the notification"
      example: "binary_sensor.my_device_power"
      selector:
        device:
          filter:
            integration: meshcentral
    message:
      required: true
      description: "The message to be sent in the notification"
      example: "Hello, World!"
      selector:
        text:
    title:
      required: false
      description: "The title of the notification"
      example: "HomeAssistant"
      selector:
        text:
